# Generated by Django 3.0.4 on 2020-04-02 10:45

from django.db import migrations
import short_stuff.django.models
import short_stuff.lib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortStuffModel',
            fields=[
                ('id', short_stuff.django.models.ShortCodeField(default=short_stuff.lib.gen_shortcode, primary_key=True, serialize=False)),
                ('test_token', short_stuff.django.models.ShortCodeField(null=True)),
            ],
        ),
    ]
